"""The points tables inside Edge_Reader.pine, and the code that writes them.

Edge Reader's expected R for a trade from the current 5-minute candle:

    gross = A + K x day_score + (sum of 5-minute points of the conditions that are true)
    day_score = DAY0 + (sum of daily points of the daily conditions that are true)
    expected R = gross - round-trip slippage in R

There is one set for longs and one for shorts. The block between `// POINTS-BEGIN` and
`// POINTS-END` in the Pine file is generated by write_points(); refit.py calls it with new numbers.
"""
import re
from pathlib import Path

import conditions as C

DAILY_NAMES = {
    "tr_up": "stock in an uptrend", "tr_dn": "stock in a downtrend", "lt_up": "above its 200-day average",
    "lt_dn": "below its 200-day average", "rng_low": "near its 20-day low", "rng_high": "near its 20-day high",
    "str_up": "stretched above its 20-day average", "str_dn": "stretched below its 20-day average",
    "nr7": "narrowest day in 7", "inside": "inside day yesterday", "d_spring": "yesterday swept a low and reclaimed it",
    "d_upthr": "yesterday swept a high and failed", "brk_up": "broke its 20-day high", "brk_dn": "broke its 20-day low",
    "bull_c": "strong green day yesterday", "bear_c": "strong red day yesterday", "vol_hi": "heavy volume yesterday",
    "vol_lo": "light volume yesterday", "buyers": "buyers led the last 5 days", "sellers": "sellers led the last 5 days",
    "rsi2_lo": "daily RSI(2) oversold", "rsi2_hi": "daily RSI(2) overbought", "rsi14_lo": "daily RSI(14) under 30",
    "rsi14_hi": "daily RSI(14) over 70", "down3": "3 down days in a row", "up3": "3 up days in a row",
    "gap_up_big": "gapped up over 1 ATR", "gap_up": "gapped up", "gap_dn": "gapped down",
    "gap_dn_big": "gapped down over 1 ATR", "open_above_pdh": "opened above yesterday's high",
    "open_below_pdl": "opened below yesterday's low", "m_tr_up": "SPY in an uptrend", "m_tr_dn": "SPY in a downtrend",
    "m_lt_up": "SPY above its 200-day", "m_lt_dn": "SPY below its 200-day", "m_rsi2_lo": "SPY oversold (RSI 2)",
    "m_rsi2_hi": "SPY overbought (RSI 2)", "m_gap_up_big": "SPY gapped up over 1 ATR",
    "m_gap_dn_big": "SPY gapped down over 1 ATR", "m_gap_up": "SPY gapped up", "m_gap_dn": "SPY gapped down",
    "m_down3": "SPY down 3 days in a row", "m_up3": "SPY up 3 days in a row", "m_str_up": "SPY stretched up",
    "m_str_dn": "SPY stretched down", "rs_up": "stronger than SPY over 20 days", "rs_dn": "weaker than SPY over 20 days",
    "mon": "Monday", "fri": "Friday", "tom": "turn of the month",
}
FIVE_MIN_NAMES = {
    "dtrend_up": "daily uptrend", "dtrend_dn": "daily downtrend", "itrend_up": "intraday uptrend",
    "itrend_dn": "intraday downtrend", "z_lt_m2": "over 2 sd below VWAP", "z_m2_m1": "1-2 sd below VWAP",
    "z_p1_p2": "1-2 sd above VWAP", "z_gt_p2": "over 2 sd above VWAP", "discount": "lower third of the day",
    "premium": "upper third of the day", "above_orh": "above the opening range", "below_orl": "below the opening range",
    "above_pdh": "above yesterday's high", "below_pdl": "below yesterday's low", "ext_up": "stretched far above the EMA",
    "ext_dn": "stretched far below the EMA", "compress": "tight range (accumulation)", "spring": "low swept and reclaimed",
    "upthrust": "high swept and rejected", "bos_up": "broke the last hour's high", "bos_dn": "broke the last hour's low",
    "bull_bar": "strong green candle", "bear_bar": "strong red candle", "rvol_lo": "quiet volume",
    "rvol_hi": "in play (1.5x volume)", "climax": "climax volume candle", "buyers": "buyers in control",
    "sellers": "sellers in control", "rsi_lo": "5-min RSI(2) oversold", "rsi_hi": "5-min RSI(2) overbought",
    "rs_up": "stronger than SPY today", "rs_dn": "weaker than SPY today", "mkt_up": "SPY above VWAP",
    "mkt_fear": "market fear day", "mkt_euph": "market euphoria day", "gap_up": "gapped up over 1 ATR",
    "gap_dn": "gapped down over 1 ATR", "t_open": "first hour", "t_lunch": "lunch hours", "t_late": "afternoon",
    "spring_up": "spring in an uptrend", "spring_disc": "spring at a discount", "bos_up_vol": "breakout with volume",
    "dip_in_trend": "deep dip in a daily uptrend", "ut_dn": "upthrust in a downtrend", "bos_dn_vol": "breakdown with volume",
}
FIVE_MIN = list(C.CONDITIONS)
assert list(FIVE_MIN_NAMES) == FIVE_MIN
BEGIN, END = "// POINTS-BEGIN", "// POINTS-END"


def _arr(values, kind):
    if kind == "float":
        items = ", ".join(f"{v:.4f}" for v in values)
    else:
        items = ", ".join('"' + v.replace('"', "'") + '"' for v in values)
    return f"array.from({items})"


def render(p):
    """p: dict with note, long/short -> {a, k, day0, day (51), five (46)} and daily_cols (51 names)."""
    assert list(p["daily_cols"]) == list(DAILY_NAMES), "daily condition order changed"
    lines = [
        f"{BEGIN} - written by research/points.py (refit.py); edit the numbers there, not here",
        f'string PTS_NOTE = "{p["note"]}"',
    ]
    for side, tag in (("long", "L"), ("short", "S")):
        s = p[side]
        assert len(s["day"]) == 51 and len(s["five"]) == 46
        lines += [f"float A_{tag} = {s['a']:.4f}", f"float K_{tag} = {s['k']:.4f}", f"float D0_{tag} = {s['day0']:.4f}",
                  f"var array<float> D_{tag} = {_arr(s['day'], 'float')}",
                  f"var array<float> P_{tag} = {_arr(s['five'], 'float')}"]
    lines += [f"var array<string> D_NAMES = {_arr(DAILY_NAMES.values(), 'str')}",
              f"var array<string> P_NAMES = {_arr(FIVE_MIN_NAMES.values(), 'str')}",
              END]
    return "\n".join(lines)


PINE_FILES = [Path(__file__).parent.parent / "pine" / n for n in ("Edge_Reader.pine", "Edge_Radar.pine")]


def write_points(pine_path, p):
    path = Path(pine_path)
    text = path.read_text()
    block = render(p)
    new, n = re.subn(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    assert n == 1, "points block not found"
    assert new.isascii()
    path.write_text(new)


def write_all(p):
    for f in PINE_FILES:
        write_points(f, p)
